### ISSUE TITLE
Issue or question about writing parquet file with short/int16

### ISSUE THREAD

**Issue by aloneguid** [aloneguid/parquet-dotnet#16]
I am so glad that this library exists!! It would be wonderful to have full functionality in supporting different data types -- I'm having issues with shorts and wonder if there is some simple mistake I am making.

**Version:** 3.0.0.0

**Runtime Version:** .Net Framework v4.5

**OS:** Windows

#### Expected behavior

When writing parquets of type short or Int16, the file should be able to be read back in without errors.

#### Actual behavior

When I try to read the file back in with parquet.net, I get error 

>  System.IO.IOException: 'not a Parquet file(head is 'R1R1')'

Trying to read it in via python with Pyarrow, I get 
>Unexpected end of stream

 I am able to read/write files with only integers and floats using these methods without any problem.

### Steps to reproduce the behavior

1. Step 1: Write a parquet file like this (this part goes through without any issue):

```csharp
//( I just changed the type of the example idColumn from the elastacloud documentation)
            var idColumn = new DataColumn(
               new DataField<Int16>("id"),
               new Int16[] { 1, 2 });

            var cityColumn = new DataColumn(
               new DataField<string>("city"),
               new string[] { "London", "Derby" });

            // create file schema
            var schema = new Schema(idColumn.Field, cityColumn.Field);

            using (Stream fileStream = System.IO.File.OpenWrite("d:\\tmp\\test.parquet"))
            {
                using (var parquetWriter = new ParquetWriter(schema, fileStream))
                {
                    // create a new row group in the file
                    using (ParquetRowGroupWriter groupWriter = parquetWriter.CreateRowGroup())
                    {
                        groupWriter.WriteColumn(idColumn);
                        groupWriter.WriteColumn(cityColumn);
                    }
                }
            }
```
2. Step 2: try to read back in:
```csharp
//
string fileNameX = @"d:\tmp\test.parquet";
Stream fs = new FileStream(fileNameX, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
var z = ParquetReader.ReadTableFromStream(fs);
```

**Comment by gsvolt** [comment]
I finally found some time to test short data type .. outcome: it is still an issue. 

In the "writing a parquet file" sample in the documentation, if you change int to short, the resulting parquet file is not valid.

In my specific use-case, I am producing the parquet file, and to validate whether the parquet file is correct or not, I am using this python command utility: [parquet-cli](https://github.com/chhantyal/parquet-cli)

I just pulled the latest (3.5.3) package of Parquet.net in an empty dotnet core command line project and wrote this code which I invite you to test on your system (notice the use of short instead of int for id):

```csharp
using System.IO;
using Parquet;
using Parquet.Data;

namespace parquet_dotnet_test
{
    class Program
    {

// This method creates a parquet file yes, but is invalid
// I am using this tool to check details about the parquet file: https://github.com/chhantyal/parquet-cli
/* Output on the console:
$ parq test.parquet 
Traceback (most recent call last):
  File "/usr/local/bin/parq", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/parq/main.py", line 38, in main
    pq_table = pq.read_table(cmd_args.file)
  File "/usr/local/lib/python2.7/dist-packages/pyarrow/parquet.py", line 1281, in read_table
    use_pandas_metadata=use_pandas_metadata)
  File "/usr/local/lib/python2.7/dist-packages/pyarrow/parquet.py", line 253, in read
    use_threads=use_threads)
  File "pyarrow/_parquet.pyx", line 1136, in pyarrow._parquet.ParquetReader.read_all
  File "pyarrow/error.pxi", line 80, in pyarrow.lib.check_status
pyarrow.lib.ArrowIOError: Unexpected end of stream
*/
        static void CreateParquetFile()
        {
            //create data columns with schema metadata and the data you need
            var idColumn = new DataColumn(
                new DataField<short>("id"),  // int type has been changed to short over here
                new short[] { 1, 2 });       // int type has been changed to short over here

            var cityColumn = new DataColumn(
                new DataField<string>("city"),
                new string[] { "London", "Derby" });

            // create file schema
            var schema = new Schema(idColumn.Field, cityColumn.Field);

            using (Stream fileStream = System.IO.File.OpenWrite("test.parquet"))
            {
                using (var parquetWriter = new ParquetWriter(schema, fileStream))
                {
                    // create a new row group in the file
                    using (ParquetRowGroupWriter groupWriter = parquetWriter.CreateRowGroup())
                    {
                        groupWriter.WriteColumn(idColumn);
                        groupWriter.WriteColumn(cityColumn);
                    }
                }
            }

        }
        static void Main(string[] args)
        {
            CreateParquetFile();
        }
    }
}

```

In your testing pipeline, I wondered if you could also inject the python parquet-cli project as I have a feeling it will give feedback for cases such as this.

Thx!

@gsvolt

**Comment by biesigrr** [comment]
You're reading/writing `INT_8`, `UINT_8`, `INT_16` and `UINT_16` incorrectly. They're supposed to be stored as `INT_32` while the DataType implementations here use the `BinaryWriter/Reader` overloads.

The R1R1 error is probably because of `File.OpenWrite` in the sample. If you created a file before and then overwrite it with changes that affect the file size (e.g. changing `int` to `short`) you'll end up with remains of the previous file after the new contents (PAR1R1 in this case). I got this error by setting `parquetWriter.CompressionMethod = CompressionMethod.None`.
