### ISSUE TITLE
ability to write custom column (chunck) data

### ISSUE THREAD

**Issue by mithom** [aloneguid/parquet-dotnet#206]
**Version:** Parquet.Net v3.10.0

**Runtime Version:** .Net Framework v4.7.2

according to https://parquet.apache.org/docs/file-format/metadata/
there is supposed to be 2 types of metadata, fileMetaData and column(chunk) metadata
it would be nice to have the option to customise the Key-value column  metadata, even if this is repeated at every column chunck.

is there a reason this is not implemented? maybe i am missing something important and there's a good reason.
Thank you already for the great project you created!

ps: sadly i am stuck in supporting .NET framework 4.7.2 due to not being allowed to upgrade by the company :( trying to push to get this done soon, but for now i will not be able to used parquet.NET v4+ due to this

**Comment by aloneguid** [comment]
@mithom you can write file level metadata (`writer.CustomMetadata` member) but not column wise at the moment. The reason is only it wasn't useful so far. You're welcome to add it.

Regarding classic .NET - it's not compatible even with .net standard 2.1 so it's a lot of effort to support by myself, especially when moving to async and memory spans to improve performance. It would essentially mean supporting two different codebases.

**Comment by aloneguid** [comment]
No worries. We might be all laid off soon and there will be no need to do anything. I'm assuming you are not in Twitter considering .NET 4.7.

**Comment by aloneguid** [comment]
Thanks, ha, i'm not from Twitter ;)

**Comment by aloneguid** [comment]
@mithom this is now [supported](https://github.com/aloneguid/parquet-dotnet/blob/master/docs/metadata.md) in the latest version ;)

**Comment by mithom** [comment]
thank you very much! next month are some rivisions to our paruet code planned, will be very usefull then!

**Comment by aloneguid** [comment]
@mithom no worries! Don't forget to star the project to boost my ego. Please.
