### ISSUE TITLE
32 bit windows no longer works with Parquet.net 4.3.2

### ISSUE THREAD

**Issue by dxdjgl** [aloneguid/parquet-dotnet#229]
**Library Version:4.3.2

**.NET Version:6.0

**OS:Windows

#### Expected Behaviour
Able to write parquet files

#### Actual Behaviour
System.DllNotFoundException: Unable to load DLL 'nironcompress': The specified module could not be found.

Most like because IronCompress does not actually include 32 bit windows dll's

### Steps to Reproduce
Create small 32 bit application

**Comment by aloneguid** [comment]
Thanks @dxdjgl this is a recurring problem, x32 is not supported now due to the fact .NET does not have a managed Snappy implementation. I have a solution which will come in the coming weeks.

Today you can either target x64 or set compression method on ParquetWriter to either Gzip or Brotli which are both managed and work everywhere.

This should be resolved soon as I'm trying to release a version fully compatible with Web Assembly (.wasm).

**Comment by aloneguid** [comment]
I think the fastest way to get it is either roll back to old version or implement yourself ;)

**Comment by dxdjgl** [comment]
I was waiting for the snappy implementation, so it seems to work with 4.3.4
