### ISSUE TITLE
[BUG]: cannot open file with column names ending in periods

### ISSUE THREAD

**Issue by MCRE-BE** [aloneguid/parquet-dotnet#278]
### Library Version

unknown

### OS

Windows

### OS Architecture

32 bit

### How to reproduce?

I am using an application (Parquet Viewer) that relies on parquet.net for reading parquet files. After I failed to open a file, I submitted a bug report there mukunku/ParquetViewer#70. The developer mentioned that the root cause was parquet.net as it seems to have an issue with column names ending in periods. 

Is this easily fixable?

The original bug report with sample file : 

**Where was the parquet file created?**
Pandas Python - 1.5.3

**Sample File**
[Example.zip](https://github.com/mukunku/ParquetViewer/files/10908532/Example.zip)

**Describe the bug**
Cannot open the file, but file can be opened in Python as the column flagged as missing is present. Likely because of a trailing "." (as that is the only mismatch between the file and the bugreport)
<img src="https://user-images.githubusercontent.com/99316631/223400700-10c51bbd-0c1a-4579-b3ec-6b15ce840e58.png" width="300">

**Screenshots**
![image](https://user-images.githubusercontent.com/99316631/223401601-120c6a66-eae8-4590-9ea7-6515546d0c1e.png)

**Comment by aloneguid** [comment]
Hey there, sorry to hear you're having trouble with those pesky dots in your path name. I know how annoying they can be. They're like little landmines waiting to explode your code.

Well, I have some good news and some sad news for you. The good news is that this is a known issue and it has been fixed in the upcoming 4.6.0 version.

The bad news is that I'm not the author of that util, so you'll have to take it upstream after the official release of 4.6.0, which should be sometime this week.

Or you could just avoid using dots in your path name altogether. That's up to you. Either way, I hope this helps and thanks for using my awesome software!

**Comment by MCRE-BE** [comment]
Top. Thanks ! I'll let the dev know that the fix is coming and that he doesn't need to make a workaround.

And yes : I do agree that we need to prevent the use of dots as much as possible, but sometimes my hands are tied to downstream code 🫣 

You can close the issue if you want or keep it open until 4.6.0 release.

**Comment by MCRE-BE** [comment]
Dev of parquet-viewer confirmed that 4.6.0 fixes the problem. Thanks !
