### ISSUE TITLE
Append in JsonSerializer

### ISSUE THREAD

**Issue by Towmeykaw** [aloneguid/parquet-dotnet#279]
### Issue description

I tried to convert from JsonConvert to JsonSerializer but noticed the append flag is removed. Is there still a way to use append?

**Comment by Towmeykaw** [comment]
My use case is that I export upwards of 25 million rows from a database and if I don't chunk it I get OOM exceptions 😄

**Comment by aloneguid** [comment]
Hey, thanks for catching this bug. I admit I was too lazy to implement this feature in the new serializer. I was hoping no one would notice it and I could get away with it.

But you did notice it and now I have to fix it. Oh well, such is life. I'll try to get it done in the next few days.

On the bright side, the new serializer should make your life easier as it reduces memory usage by writing data in chunks per column (class property). That means you can process more data without crashing your computer. Isn't that awesome?

**Comment by aloneguid** [comment]
Hey. Because you asked, I've added support for append operations in v4.6.1. Please check it out! Now you can easily add more data to your files without overwriting them. But be careful not to append too much or you might run out of disk space. And don't forget to backup your files before you try this new feature. You never know what might go wrong.

Link to docs: https://github.com/aloneguid/parquet-dotnet/blob/master/docs/serialisation.md#appending-to-files

I hope you enjoy this update and let me know if you have any feedback or issues. Cheers!

**Comment by aloneguid** [comment]
It took me only 10 minutes to code this masterpiece, and I'm sure you're impressed by my speedy work and want to show your appreciation. Well, there's an easy way to do that: just star the project!

It's a simple gesture that means a lot to me. Plus, it will boost my ego and motivate me to create more stuff for you.

So don't forget to star the project if you like my speedy work! Or else...

**Comment by Towmeykaw** [comment]
No problem at all. The amount of time and sanity this library has saved from not having to run python scripts in AWS Glue is priceless 😄

**Comment by Towmeykaw** [comment]
Thanks for the awesome work. My data team will be very happy and I won't have to run manual data exports all weekend 😄
