### ISSUE TITLE
[BUG]: Nested nulls can be interpreted at the wrong level 

### ISSUE THREAD

**Issue by jmandel** [aloneguid/parquet-dotnet#282]
### Library Version

4.6.1

### OS

Linux

### OS Architecture

64 bit

### How to reproduce?

I'm encountering problems with serialization of nested null values. Results of serialization->deserialiation can interpret the null at the wrong level.

I encountered issues working with the Table API  with nested arrays, but when I tried to put together a minimal breaking example, I found this relatively simple case that leads to failure with the Class API, without arrays.

### Failing test

Try this test in `ParquetSerializerTest.cs`:

```csharp
        [Fact]
        public async Task Struct_Serde_With_NestedNulls() {

            var data = new List<AddressBookEntry> {
                new AddressBookEntry {
                    FirstName = "Joe",
                    LastName = "Bloggs",
                    Address = new Address() {
                        City = null,
                        Country = null
                    }
                }
            };

            using var ms = new MemoryStream();
            await ParquetSerializer.SerializeAsync(data, ms);

            ms.Position = 0;
            IList<AddressBookEntry> data2 = await ParquetSerializer.DeserializeAsync<AddressBookEntry>(ms);

            Assert.Equivalent(data2, data);
        }
```

This tests should succeed, but it fails with

```sh
[xUnit.net 00:00:01.16]     Parquet.Test.Serialisation.ParquetSerializerTest.Struct_Serde_With_NestedNulls [FAIL]
  Failed Parquet.Test.Serialisation.ParquetSerializerTest.Struct_Serde_With_NestedNulls [269 ms]
  Error Message:
   Assert.Equivalent() Failure: Collection value not found
Expected: AddressBookEntry { Address = null, FirstName = "Joe", LastName = "Bloggs" }
In:       [AddressBookEntry { Address = Address { ... }, FirstName = "Joe", LastName = "Bloggs" }]
  Stack Trace:
     at Parquet.Test.Serialisation.ParquetSerializerTest.Struct_Serde_With_NestedNulls() in /tmp/parquet-dotnet/src/Parquet.Test/Serialisation/ParquetSerializerTest.cs:line 118
--- End of stack trace from previous location ---

Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: < 1 ms - Parquet.Test.dll (net7.0)
```

**Comment by thomas-bios** [comment]
@aloneguid I've updated my comment, added the repetition level of the column and a precision.

The goal here is to recreate the matrix of a column using _repetition level_. [Point 4 of this doc](https://github.com/aloneguid/parquet-dotnet/blob/aeac9ee3ff42ef938bd6b331ff28e4abaf142c7b/docs/reading.md)

We must use the repetition level to know when to move to the next line or to continue happening to the actual line.
If I have:
`   | col1       |`
`v1 | [a, b, c]  |`
`v2 | null       |`
`v3 | [d, e, f]  |`

I should have what I have in 3.x when reading `.Data` and what I have in both version when reading `.RepetitionLevels`

**Comment by aloneguid** [comment]
@thomas-bios still not with you. A failing unit test may be the best to show the issue.

**Comment by Mrinal-Thomas-Epic** [comment]
@aloneguid I think the issue is that for optional fields. In [`UntypeArrayExtensions.cs`](https://github.com/aloneguid/parquet-dotnet/blob/master/src/Parquet/Extensions/UntypedArrayExtensions.cs#L484) when packing null values, you are setting definition level to either max DL (when the value is defined) or 0 (when the value is null). To support nested optional structures in parquet, you have to set the DL based on the level at which the value is not defined.

My recommendation would be:
1) [`ParquetSerializer.SerializeAsync`](https://github.com/aloneguid/parquet-dotnet/blob/master/src/Parquet/Extensions/UntypedArrayExtensions.cs#L484) should pass in false for the `unpackDefinitions` parameter when creating a `DataColumn`.
1.1) The DataColumn constructor that takes in definition levels should be made public, so that consumers of the column-based API can provide definition levels.
2) If [`PackedColumn.Pack`](https://github.com/aloneguid/parquet-dotnet/blob/master/src/Parquet/File/PackedColumn.cs#L145) is called with a `DataColumn` that already has definition levels, use the existing definitions levels.

**Comment by Mrinal-Thomas-Epic** [comment]
For an example that doesn't work, I ran the below code to write parquet files.
```
public class Solution
{
		public static async Task Main(string[] args)
		{
			List<A> myRecords = new();
			myRecords.Add(new A("first", new B[] { new B(4), new B(5), new B(6) }));
			myRecords.Add(new A("second", new List<B>() { new B(8), new B(0), new B(8) }));
			myRecords.Add(new A(null, new List<B>() { }));
			myRecords.Add(new A("third", new B[] { new B(1000), new B(2000), new B(3000) }));
			await ParquetSerializer.SerializeAsync(myRecords, "my-file-with-nulls.parquet");
			
		}
}

public class A
{ 
	public string StringProp { get; set; }

	public IEnumerable<B> ListStructProp { get; set; }

	public A(string strProp, IEnumerable<B> lstProp)
	{
		ListStructProp = lstProp;
		StringProp = strProp;
	}
}

public class B
{
	public int IntProp { get; set; }

	public B(int intProp)
	{
		IntProp = intProp;
	}
}
```

Then, if I try to view it in Parquet Viewer website, I get an incorrect result:
![image](https://user-images.githubusercontent.com/126519671/230804245-9c1afa13-7598-4c57-8d4a-8db6be7345ca.png)

**Comment by Mrinal-Thomas-Epic** [comment]
Sorry for the late reply. Thanks for the quick fix!
