### ISSUE TITLE
Unable to write a column with a Date logical type

### ISSUE THREAD

**Issue by akamor** [aloneguid/parquet-dotnet#54]
**Version:** Parquet.Net v3.6

**Runtime Version:** .Net Core v3.0

**OS:** Windows

#### Expected behavior

When writing values to a column whose schema is a int32 with a Date logical type I'd expect to be able to write int32 values to the column since the Date logical type stores the # of days since epoch time.

#### Actual behavior

I can only write values to the column as DateTimeOffset and they get written to the column with the teimstamp[ns] logical type instead.

Perhaps I am misunderstanding something, but I first open a file which has a int32 column and a logical Date type.  I then use that files schema to create a new file and ParquetWriter.  My goal is to write new column values of different dates but instead I can only write timestamps.

Am I perhaps mis-using the library?

**Comment by akamor** [comment]
To clarify on this a bit more.  When I create a DataColumn that has a DateTimeDataField and I use a DateTimeFormat of Date I'd expect to be able to write integers to the data column (since those integers would represent the # of days since 1970-1-1 according to the parquet documentation).

But instead, I can only write DateTimeOffset objects and when I write them the resulting parquet file doesn't have the LogicalType I expect (Date).  Instead it has a LogicalType of timestamp with a resolution of nanoseconds.

**Comment by skyyearxp** [comment]
may be just by design.

https://github.com/aloneguid/parquet-dotnet/blob/develop/doc/schema.md
new DateTimeDataField("date_col", DateTimeFormat.Date);

in test case, equal test. it's based on DateTimeOffset.
// don't want any excess info in the offset INT32 doesn't contain or care about this data 
["dateDate"] = (new DateTimeDataField("dateDate", DateTimeFormat.Date), new DateTimeOffset(DateTime.UtcNow.RoundToDay(), TimeSpan.Zero)),
